stat_p.py:73: RuntimeWarning: invalid value encountered in sqrt
  sd_b = np.sqrt(var_b)
****************************************
STREPTOMYCIN   loader dataset ...
(2980, 314566)
(2980,)
{0, 1}
=====xgb=======
 finish ... 
 finish ... 
 finish ... 
****************************************
PYRAZINAMIDE   loader dataset ...
(4234, 314566)
(4234,)
{0, 1}
=====xgb=======
 finish ... 
 finish ... 
 finish ... 
****************************************
ETHIONAMIDE   loader dataset ...
(779, 314566)
(779,)
{0, 1}
=====xgb=======
 finish ... 
 finish ... 
 finish ... 
****************************************
ETHAMBUTOL   loader dataset ...
(4921, 314566)
(4921,)
{0, 1}
=====xgb=======
 finish ... 
 finish ... 
 finish ... 
****************************************
AMIKACIN   loader dataset ...
(2074, 314566)
(2074,)
{0, 1}
=====xgb=======
Traceback (most recent call last):
  File "stat_p.py", line 222, in <module>
    x.ensemble_methods('xgb', str(drug))
  File "stat_p.py", line 72, in ensemble_methods
    var_b = MSE*(np.linalg.inv(np.dot(newX.T,newX)).diagonal())
  File "<__array_function__ internals>", line 6, in inv
  File "/home/gongxj/anaconda3/envs/tju/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 546, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/gongxj/anaconda3/envs/tju/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
stat_p.py:73: RuntimeWarning: invalid value encountered in sqrt
  sd_b = np.sqrt(var_b)
****************************************
KANAMYCIN   loader dataset ...
(1633, 93313)
(1633,)
{0, 1}
=====xgb=======
 finish ... 
Traceback (most recent call last):
  File "stat_p.py", line 222, in <module>
    x.ensemble_methods('xgb', str(drug))
  File "stat_p.py", line 72, in ensemble_methods
    var_b = MSE*(np.linalg.inv(np.dot(newX.T,newX)).diagonal())
  File "<__array_function__ internals>", line 6, in inv
  File "/home/gongxj/anaconda3/envs/tju/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 546, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/gongxj/anaconda3/envs/tju/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
stat_p.py:74: RuntimeWarning: divide by zero encountered in true_divide
  ts_b = params/ sd_b
stat_p.py:74: RuntimeWarning: invalid value encountered in true_divide
  ts_b = params/ sd_b
stat_p.py:73: RuntimeWarning: invalid value encountered in sqrt
  sd_b = np.sqrt(var_b)
****************************************
MOXIFLOXACIN   loader dataset ...
(1488, 56647)
(1488,)
{0, 1}
=====xgb=======
 finish ... 
 finish ... 
 finish ... 
****************************************
RIFABUTIN   loader dataset ...
(307, 28964)
(307,)
{0, 1}
=====xgb=======
Traceback (most recent call last):
  File "stat_p.py", line 222, in <module>
    x.ensemble_methods('xgb', str(drug))
  File "stat_p.py", line 72, in ensemble_methods
    var_b = MSE*(np.linalg.inv(np.dot(newX.T,newX)).diagonal())
  File "<__array_function__ internals>", line 6, in inv
  File "/home/gongxj/anaconda3/envs/tju/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 546, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/gongxj/anaconda3/envs/tju/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
stat_p.py:73: RuntimeWarning: invalid value encountered in sqrt
  sd_b = np.sqrt(var_b)
****************************************
ISONIAZID   loader dataset ...
(5300, 236475)
(5300,)
{0, 1}
=====xgb=======
 finish ... 
 finish ... 
 finish ... 
****************************************
OFLOXACIN   loader dataset ...
(2306, 102795)
(2306,)
{0, 1}
=====xgb=======
 finish ... 
 finish ... 
 finish ... 
****************************************
PROTHIONAMIDE   loader dataset ...
(502, 13309)
(502,)
{0, 1}
=====xgb=======
 finish ... 
 finish ... 
 finish ... 
****************************************
CIPROFLOXACIN   loader dataset ...
(358, 37692)
(358,)
{0, 1}
=====xgb=======
Traceback (most recent call last):
  File "stat_p.py", line 222, in <module>
    x.ensemble_methods('xgb', str(drug))
  File "stat_p.py", line 72, in ensemble_methods
    var_b = MSE*(np.linalg.inv(np.dot(newX.T,newX)).diagonal())
  File "<__array_function__ internals>", line 6, in inv
  File "/home/gongxj/anaconda3/envs/tju/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 546, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/gongxj/anaconda3/envs/tju/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
stat_p.py:73: RuntimeWarning: invalid value encountered in sqrt
  sd_b = np.sqrt(var_b)
****************************************
RIFAMPICIN   loader dataset ...
(5076, 236382)
(5076,)
{0, 1}
=====xgb=======
 finish ... 
 finish ... 
 finish ... 
****************************************
CAPREOMYCIN   loader dataset ...
(2126, 101730)
(2126,)
{0, 1}
Traceback (most recent call last):
  File "stat_p.py", line 222, in <module>
    x.ensemble_methods('xgb', str(drug))
  File "stat_p.py", line 37, in ensemble_methods
    feat = pd.read_csv("./dataset_pff/xgb/"+str(drug)+"_imp.csv")
  File "/home/gongxj/anaconda3/envs/tju/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/gongxj/anaconda3/envs/tju/lib/python3.6/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/gongxj/anaconda3/envs/tju/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/gongxj/anaconda3/envs/tju/lib/python3.6/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/gongxj/anaconda3/envs/tju/lib/python3.6/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'./dataset_pff/xgb/CAPREOMYCIN_imp.csv' does not exist: b'./dataset_pff/xgb/CAPREOMYCIN_imp.csv'
****************************************
AMIKACIN   loader dataset ...
(2074, 87470)
(2074,)
{0, 1}
=====xgb=======
Traceback (most recent call last):
  File "stat_p.py", line 206, in <module>
    x.ensemble_methods('xgb', str(drug))
  File "stat_p.py", line 118, in ensemble_methods
    acc,sen,sps,roc_auc=self.performance_calculation(tel,prr,pred)
AttributeError: 'EnsembleLearning' object has no attribute 'performance_calculation'
